---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
```

read data

```{r}
cake_data <- read_csv(here::here("clean_data/cake_data_clean.csv"))
```


Q1. Which cake has the most cocoa in it?

```{r}
cake_data %>% 
  filter(ingredient == "Cocoa") %>% 
  slice_max(amount)
```


Q2. For sponge cake, how many cups of ingredients are used in total?

```{r}
cake_data %>% 
  filter(cake == "Sponge" & measure == "cup") %>% 
  summarise(total_cups_sponge = sum(amount, na.rm= TRUE))
```


Q3. How many ingredients are measured in teaspoons?

```{r}
cake_data %>% 
  filter(measure == "teaspoon") %>% 
  distinct(ingredient) %>% 
  summarise(number_using_teaspons = n())
```


Q4. Which cake has the most unique ingredients?

```{r}
cake_data %>% 
  drop_na(amount) %>% 
  group_by(cake) %>% 
  summarise(number_of_ingredients = n()) %>% 
  slice_max(number_of_ingredients)
```


Q5. Which ingredients are used only once?

```{r}
cake_data %>%
  drop_na(amount) %>% 
  count(ingredient) %>% 
  filter(n == 1)
```








