---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse)
library(janitor)
library(stringr)
library(readxl)
```


```{r}
usa_group_extras <- c(
  "murica",
  "the best one - usa",
  "the yoo ess of aaayyyyyy",
  "sub-canadian north america... 'merica",
  "trumpistan",
  "merica",
  "north carolina",
  "'merica",
  "pittsburgh",
  "new york",
  "california",
  "i pretend to be from canada, but i am really from the united states.",
  "ahem....amerca",
  "new jersey",
  "murrika",
  "alaska"
)


uk_group_extras <- c("england", 
                     "scotland")

spain_group <- c("espa単a", "spain")
south_korea_group <- c("south korea", "korea")
netherlands_group <- c("the netherlands", "netherlands")
canada_group <- c("canada", "can", "canada`")
other_valid_countries <-
  c(
    "japan",
    "france",
    "switzerland",
    "belgium",
    "croatia",
    "portugal",
    "espa単a",
    "spain",
    "panama",
    "australia",
    "hungary",
    "austria",
    "new zealand",
    "germany",
    "mexico",
    "brasil",
    "philippines",
    "sweden",
    "finland",
    "china",
    "kenya",
    "uae",
    "costa rica",
    "greece",
    "ireland",
    "south africa",
    "iceland",
    "denmark",
    "singapore",
    "taiwan",
    "hong kong"
  )
```




```{r}
countries <- bind_rows(candy_2015_piv, candy_2016_piv, candy_2017_piv) %>% 
  mutate(country = str_to_lower(country)) %>% 
  count(country)
  
countries_name_list <- countries %>%
  mutate(country_2 = case_when(
    str_detect(country, "^usa") ~ "usa",
    str_detect(country, "^u[ ]*s") ~ "usa",
    str_detect(country, "^u\\.s\\.") ~ "usa",
    str_detect(country, "^united[ ]+s") ~ "usa",
    str_detect(country, "^u[a-z ]+ states") ~ "usa",
    str_detect(country, "^the united states") ~ "usa",
    str_detect(country, "^america") ~ "usa")) %>% 
  mutate(country_2 = case_when(
    country %in% other_valid_countries ~ country,
    TRUE ~ country_2)) %>%
  mutate(country_2 = case_when(
    country %in% spain_group ~ "spain",
    TRUE ~ country_2)) %>%
  mutate(country_2 = case_when(
    country %in% south_korea_group ~ "south korea",
    TRUE ~ country_2)) %>%
  mutate(country_2 = case_when(
    country %in% netherlands_group ~ "netherlands",
    TRUE ~ country_2)) %>%
  mutate(country_2 = case_when(
    str_detect(country, "united k") ~ "uk",
    str_detect(country, "^u[\\.]*k") ~ "uk",
    TRUE ~ country_2)) %>%
  mutate(country_2 = case_when(
    str_detect(country, "canada") ~ "canada",
    TRUE ~ country_2)) %>% 
  select(country, country_2, n) 

discarded_countries <- countries_name_list %>% 
  filter(is.na(country_2))



```


```{r}

usa_group_standard <- countries_name_list %>% filter(country_2 == "usa") %>% pull(country)
usa_group <- c(usa_group_standard, usa_group_extras)


uk_group_standard <- countries_name_list %>% filter(country_2 == "uk") %>% pull(country)
uk_group <- c(uk_group_standard, uk_group_extras)

spain_group <- c("espa単a", "spain")
south_korea_group <- c("south korea", "korea")
netherlands_group <- c("the netherlands", "netherlands")
canada_group <- c("canada", "can", "canada`")
other_valid_countries <- c("japan", "france", "switzerland", "belgium", 
                           "croatia", "portugal", "espa単a", "spain", "panama", 
                           "australia", "hungary", "austria", "new zealand", 
                           "germany", "mexico", "brasil", "philippines", 
                           "sweden", "finland", "china", "kenya", "uae", 
                           "costa rica", "greece", "ireland", "south africa", 
                           "iceland", "denmark", "singapore", "taiwan", 
                           "hong kong")


rm(countries_name_list, countries, usa_group_standard, usa_group_extras, uk_group_extras, uk_group_standard)

```

