---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse)
library(janitor)
library(stringr)
library(readxl)
```


```{r}
candy_2015 <- read_excel(here::here("raw_data/boing-boing-candy-2015.xlsx"))
candy_2016 <- read_excel(here::here("raw_data/boing-boing-candy-2016.xlsx"))
candy_2017 <- read_excel(here::here("raw_data/boing-boing-candy-2017.xlsx"))



```



```{r}
names(candy_2015)
names(candy_2016)
names(candy_2017)
```

```{r}
clean_names(candy_2015)
clean_names(candy_2016)
clean_names(candy_2017)


```
# name cleaning 2015

```{r}
names(candy_2015)

candy_2015_piv <- candy_2015 %>% 
  select(c(2:96)) %>% 
  mutate(year = 2015, 
         id = c(paste0(1:(nrow(candy_2015)), "_", 2015)),
         country = as.character(NA),
         gender = as.character(NA)) %>% 
  rename(age = "How old are you?",
         going_out = "Are you going actually going trick or treating yourself?",
         "[JoyJoy (Mit Iodine!)]" = "[JoyJoy (Mit Iodine)]") %>% 
  select(id, year, going_out, gender, age, country, c(3:95)) %>% 
  rename_all(~ str_to_lower(.)) %>%
  pivot_longer(cols = c("[butterfinger]":"[york peppermint patties]"),
               names_to = "candy",
               values_to = "rating") %>% 
  mutate(candy = str_sub(candy, 2, -2))

?pivot_longer
  
```



# name cleaning 2016

```{r}
names(candy_2016)

candy_2016_piv <- candy_2016 %>% 
  select(c(2:106)) %>% 
  mutate(year = 2016,
         id = c(paste0(1:(nrow(candy_2016)), "_", 2016))) %>% 
  select(id, year, c(1:4, 6:105)) %>% 
  rename(going_out = "Are you going actually going trick or treating yourself?",
         gender = "Your gender:",
         age = "How old are you?",
         country = "Which country do you live in?",
         "[box’o’ raisins]" = "[Box'o'Raisins]") %>% 
  rename_all(~ str_to_lower(.)) %>%
  pivot_longer(cols = c("[100 grand bar]":"[york peppermint patties]"),
               names_to = "candy",
               values_to = "rating") %>% 
  mutate(candy = str_sub(candy, 2, -2)) 
  


```


# name cleaning 2017

```{r}
names(candy_2017)

candy_2017_piv <- candy_2017 %>% 
  select(c(2:109)) %>% 
  mutate(year = 2017,
         id = c(paste0(1:(nrow(candy_2017)), "_", 2017))) %>%
  select(id, year, c(1:4, 6:108)) %>%
  rename_all(~ str_replace(., "^Q[0-9]: ", "")) %>% 
  rename_all(~ str_to_lower(.)) %>%
  rename("q6 | anonymous brown globs that come in black and orange wrappers" = 
           "q6 | anonymous brown globs that come in black and orange wrappers	(a.k.a. mary janes)",
         "q6 | box’o’ raisins" = "q6 | box'o'raisins")   %>% 
  pivot_longer(cols = c("q6 | 100 grand bar":"q6 | york peppermint patties"),
               names_to = "candy",
               values_to = "rating") %>% 
  mutate(candy = str_sub(candy, 6)) %>% 
  clean_names()
  

  


```

# year inv 

```{r}
bind_rows(candy_2015_piv, candy_2016_piv, candy_2017_piv) %>% 
  count(country)
```



# ages inv 

```{r}
bind_rows(candy_2015_piv, candy_2016_piv, candy_2017_piv) %>% 
  count(format(round(as.numeric(age)), scientific = FALSE))

bind_rows(candy_2015_piv, candy_2016_piv, candy_2017_piv) %>% 
  mutate(age = round(as.numeric(age)),
         age = case_when(age < 101 & age > 5 ~ age,
                         TRUE ~ 0),
         age = na_if(age, 0)) %>% 
  count(age)
        


```



# gender inv 

```{r}
bind_rows(candy_2015_piv, candy_2016_piv, candy_2017_piv) %>% 
  distinct(gender)
```

# going_out inv 

```{r}
bind_rows(candy_2015_piv, candy_2016_piv, candy_2017_piv) %>% 
  distinct(going_out)
```

# candy inv 

```{r}
bind_rows(candy_2015_piv, candy_2016_piv, candy_2017_piv) %>%
 filter(str_detect(candy, "anon") | str_detect(candy, "mary")) %>% 
 count(candy)

bind_rows(candy_2015_piv, candy_2016_piv, candy_2017_piv) %>%
 count(candy) %>% 
 arrange(candy)

# anonymous_brown.. = mary janes
# x100_grand_bar = 100_grand_bar
#jolly rancher good and bad
#box_o_raisins
```


# candy inv 

```{r}

bind_rows(candy_2015_piv, candy_2016_piv, candy_2017_piv) %>%
  mutate(country = tolower(country)) %>% 
  filter(str_detect(country, "^us") |
         str_detect(country, "^u\\.s") |
         str_detect(country, "united s") |
         str_detect(country, "^[']*m[eu]rica") |
         str_detect(country, "not[.]* usa")) %>% 
  distinct(country)

bind_rows(candy_2015_piv, candy_2016_piv, candy_2017_piv) %>%
  mutate(country = tolower(country)) %>% 
  filter(!str_detect(country, "^us") &
         !str_detect(country, "^u\\.s") &
         !str_detect(country, "united s") &
         !str_detect(country, "^[']*m[eu]rica") &
         !str_detect(country, "not[.]* usa")) %>% 
  distinct(country)


bind_rows(candy_2015_piv, candy_2016_piv, candy_2017_piv) %>%
  mutate(country = tolower(country)) %>%
  count(country)

  


```



```{r}
bind_rows(candy_2015_piv, candy_2016_piv, candy_2017_piv) %>%
  mutate(country = tolower(country)) %>% 
  filter(str_detect(country, "^us") |
         str_detect(country, "^u\\.s") |
         str_detect(country, "united s") |
         str_detect(country, "^[']*m[eu]rica") |
         str_detect(country, "not[.]* usa")) %>% 
  distinct(country) 

bind_rows(candy_2015_piv, candy_2016_piv, candy_2017_piv) %>%
  mutate(country = tolower(country)) %>% 
  filter(!str_detect(country, "^us") &
         !str_detect(country, "^u\\.s") &
         !str_detect(country, "united s") &
         !str_detect(country, "^[']*m[eu]rica") &
         !str_detect(country, "not[.]* usa")) %>% 
  distinct(country)

```

```{r}
usa_group <- c("usa", "us", "united states of america", "united states", "ussa", "u.s.a.", "murica", "usa!", "usa (i think but it's an election year so who can really tell)", "u.s.", "america", "units states", "usa usa usa", "the best one - usa", "usa! usa! usa!", "the yoo ess of aaayyyyyy", "usa!!!!!!", "usa! usa!", "united sates", "sub-canadian north america... 'merica", "trumpistan", "merica", "united stetes", "usa usa usa usa", "united states of america", "united state", "united staes", "usausausa", "us of a", "unites states", "the united states", "north carolina", "unied states", "u s", "the united states of america", "unite states", "'merica", "usas", "pittsburgh", "new york", "california", "i pretend to be from canada, but i am really from the united states.", "united stated", "ahem....amerca", "new jersey", "united ststes", "united statss", "murrika", "usaa", "alaska", "u s a", "united statea", "usa usa usa!!!!", "united states of america")

usa_group
```

```{r}
uk_group <- c("uk", "england", "united kingdom", "united kindom", "u.k.", "scotland")
spain_group <- c("españa", "spain")
south_korea_group <- c("south korea", "korea")
netherlands_group <- c("the netherlands", "netherlands")
canada_group <- c("canada", "can", "canada`")
other_valid_countries <- c("japan", "france", "switzerland", "belgium", "croatia", "portugal", "españa", "spain", "panama", "australia", "hungary", "austria", "new zealand", "germany", "mexico", "brasil", "philippines", "sweden", "finland", "china", "kenya", "uae", "costa rica", "greece", "ireland", "south africa", "iceland", "denmark", "singapore", "taiwan", "hong kong")
```



```{r}

bind_rows(candy_2015_piv, candy_2016_piv, candy_2017_piv) %>% 
  mutate(country = tolower(country),
         country =
           case_when(
             country %in% usa_group ~ "usa",
             country %in% uk_group ~ "uk",
             country %in% spain_group ~ "spain",
             country %in% south_korea_group ~ "south korea",
             country %in% netherlands_group ~ "netherlands",
             country %in% canada_group ~ "canada",
             country %in% other_valid_countries ~ country,
             TRUE ~ "unknown"
           ),
         country = na_if(country, "unknown")
  ) %>% count(country)






```



```{r}
bind_rows(candy_2015_piv, candy_2016_piv, candy_2017_piv) %>%
  mutate(
    country = tolower(country),
    country =
      case_when(
        country %in% usa_group ~ "usa",
        country %in% uk_group ~ "uk",
        country %in% spain_group ~ "spain",
        country %in% south_korea_group ~ "south korea",
        country %in% netherlands_group ~ "netherlands",
        country %in% canada_group ~ "canada",
        country %in% other_valid_countries ~ country,
        TRUE ~ "unknown"
      ),
    country = na_if(country, "unknown")
  ) %>%  
  mutate(
    age = case_when(str_detect(age, "[!A-z\\+\\-\\>\\<\\?]") ~ "0",
                    TRUE ~ age))%>% 
  count(age)

bind_rows(candy_2015_piv, candy_2016_piv, candy_2017_piv) %>%
   mutate(age = case_when(
    str_detect(age, "![A-z]") ~ ,
    TRUE ~ "0")) %>% 
  count(age)
  

   age = round(as.numeric(age)),
    age = case_when(age < 101 & age > 5 ~ age,
                    TRUE ~ 0),
    age = na_if(age, 0)
  ) 
 

candy_data %>% 
  count(going_out)


```




```{r}
candy_2015 %>% 
  select(`How old are you?`, `Please list any items not included above that give you JOY.`, `Please list any items not included above that give you DESPAIR.` )
```




